server:
  port: 8080

spring:
  application:
    name: accounts

  profiles:
    active: "prod"

  datasource:
    url: jdbc:h2:mem:apexdb
    username: apex
    password: uchiha
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  config:
    import: "configserver:http://localhost:8071/"

  cloud:
    bus:
      enabled: false

#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    service-url:
      defaultZone: "http://localhost:8070/eureka/"

info:
  app:
    name: "accounts"
    description: "Apex Bank Accounts Application"
    version: "1.0"



