spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "2.0"

accounts:
  message: "Welcome to ApexBank cards related local APIs"
  contactDetails:
        name: "Apex Uchiha - Product Owner"
        email: "uchiha@apexbank.com"
  onCallSupport:
  - (555) 555-1234
  - (555) 523-1345 
