services:
  accounts:
    image: "apexhunt/accounts:v1"
    container_name: accountsApex
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - apexbank
  loans:
    image: "apexhunt/loans:v1"
    container_name: loansApex
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - apexbank
  cards:
    image: "apexhunt/cards:v1"
    container_name: cardsApex
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - apexbank
networks:
  apexbank:
    driver: "bridge"